name: Set Branch Protection
on:
  workflow_dispatch:
jobs:
  set-protection:
    runs-on: cldcvr-pvt-runner-aws
    steps:
      - name: Set up branch protection
        run: |
          run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.OLLION_BRANCH_PROTECTION_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/branches/main/protection" \
            -d '{
            "required_status_checks": null,
            "enforce_admins": null,
            "required_pull_request_reviews": {
              "required_approving_review_count": 1
            },
            "restrictions": null,
            "required_conversation_resolution": true,
            "required_signatures": true
          }'
